---
#! Source: gha-runner-scale-set/templates/kube_mode_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-runner-gha-rs-kube-mode
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems

  finalizers:
    - actions.github.com/cleanup-protection
---
#! Source: gha-runner-scale-set/templates/githubsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: arc-runner-gha-rs-github-secret
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
data:
  github_token: cGxhY2Vob2xkZXI=
---
#! Source: gha-runner-scale-set/templates/kube_mode_role.yaml
# default permission for runner pod service account in kubernetes mode (container hook)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-gha-rs-kube-mode
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch",]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
---
#! Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
#! Source: gha-runner-scale-set/templates/kube_mode_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-gha-rs-kube-mode
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems

  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-gha-rs-kube-mode
subjects:
- kind: ServiceAccount
  name: arc-runner-gha-rs-kube-mode
  namespace: arc-systems
---
#! Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role-binding
  annotations:
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: arc-runner-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    arc-gha-rs-controller
  namespace: 
    arc-systems
---
#! Source: hook-extension-configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: privileged-hook-extension-arc-runner
  namespace: arc-systems
data:
  content: ""
---
#! Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: arc-runner
  namespace: arc-systems
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.13.0
    app.kubernetes.io/name: arc-runner
    app.kubernetes.io/instance: arc-runner
    app.kubernetes.io/version: "0.13.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: arc-runner
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
    actions.github.com/values-hash: f62934090dccf2f9c02d83727ab9f536d70f8b31bfdb1124d8f557270a314d7
    actions.github.com/cleanup-github-secret-name: arc-runner-gha-rs-github-secret
    actions.github.com/cleanup-manager-role-binding: arc-runner-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: arc-runner-gha-rs-manager
    actions.github.com/cleanup-kubernetes-mode-role-binding-name: arc-runner-gha-rs-kube-mode
    actions.github.com/cleanup-kubernetes-mode-role-name: arc-runner-gha-rs-kube-mode
    actions.github.com/cleanup-kubernetes-mode-service-account-name: arc-runner-gha-rs-kube-mode

spec:
  githubConfigUrl: https://github.com/example/repo
  githubConfigSecret: arc-runner-gha-rs-github-secret

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: arc-runner-gha-rs-kube-mode
      containers:
      - name: runner
        
        command: 
          - /home/runner/run.sh
        image: 
          ghcr.io/actions/actions-runner:latest
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
            value: /home/runner/k8s/index.js
          - name: ACTIONS_RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "true"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
      
      volumes:
      
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: standard
